install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt\sbt\bin" )) {
        if (Test-Path -Path "C:\sbt") {
          Remove-Item C:\sbt -Force -Recurse
        }
        (new-object System.Net.WebClient).DownloadFile(
          'https://github.com/sbt/sbt/releases/download/v1.1.2/sbt-1.1.2.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET JDK_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET PATH=C:\sbt\sbt\bin;%JDK_HOME%\bin;%PATH%
build_script:
  - sbt compile test scripted
cache:
  - C:\sbt\
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2